import type { DestinationData } from "@/types/destination";

export const destinationData: Record<string, DestinationData> = {
  goa: {
    overview: {
      description:
        "India's smallest state by area, Goa is a dazzling blend of sun-kissed beaches, Portuguese colonial architecture, vibrant nightlife, and rich culinary traditions along the Arabian Sea coast.",
      bestTimeToVisit: "November to February",
      language: "Konkani, English, Hindi",
      currency: "INR (₹)",
      timeZone: "IST (UTC+5:30)",
      quickFacts: [
        { label: "Population", value: "1.5M" },
        { label: "Area", value: "3,702 km²" },
        { label: "Coastline", value: "160 km" },
        { label: "Known for", value: "Beaches, nightlife, seafood" },
      ],
    },
    weather: {
      current: {
        temp: 28,
        condition: "Sunny",
        icon: "sun",
        humidity: 74,
        windSpeed: 12,
      },
      forecast: [
        { date: "2026-07-15", tempHigh: 31, tempLow: 25, condition: "Sunny" },
        { date: "2026-07-16", tempHigh: 30, tempLow: 24, condition: "Partly Cloudy" },
        { date: "2026-07-17", tempHigh: 29, tempLow: 24, condition: "Thunderstorms" },
        { date: "2026-07-18", tempHigh: 28, tempLow: 23, condition: "Showers" },
        { date: "2026-07-19", tempHigh: 30, tempLow: 25, condition: "Sunny" },
      ],
    },
    food: [
      {
        name: "Goan Fish Curry",
        description: "A tangy coconut-based curry made with fresh kingfish, kokum, and local spices",
        category: "Signature Dish",
        priceRange: "₹200 - ₹400",
        restaurant: "Fisherman's Wharf, Panjim",
        tags: ["seafood", "must-try", "lunch"],
      },
      {
        name: "Prawn Balchão",
        description: "Spicy pickled prawns in a fiery red masala — a Goan-Portuguese classic",
        category: "Starter",
        priceRange: "₹250 - ₹450",
        tags: ["seafood", "spicy", "starter"],
      },
      {
        name: "Bebinca",
        description: "Traditional Goan dessert with 16 layers of coconut milk, eggs, and jaggery",
        category: "Dessert",
        priceRange: "₹100 - ₹200",
        restaurant: "Cafe Tato, Panjim",
        tags: ["dessert", "traditional", "must-try"],
      },
      {
        name: "Feni",
        description: "Local cashew or coconut spirit with a distinct kick. Served neat or on the rocks",
        category: "Beverage",
        priceRange: "₹80 - ₹150 per peg",
        tags: ["alcohol", "local", "traditional"],
      },
      {
        name: "Chicken Xacuti",
        description: "Rich, aromatic curry made with roasted coconut, poppy seeds, and red chilies",
        category: "Main Course",
        priceRange: "₹250 - ₹400",
        tags: ["curry", "spicy", "dinner"],
      },
    ],
    attractions: [
      {
        name: "Baga Beach",
        description: "One of Goa's most popular beaches with water sports, shacks, and vibrant nightlife",
        category: "Beach",
        approximateCost: 0,
        duration: "2-4 hours",
        bestTime: "Morning or late afternoon",
      },
      {
        name: "Basilica of Bom Jesus",
        description: "UNESCO World Heritage site housing the relics of St. Francis Xavier. Baroque architecture at its finest",
        category: "Heritage",
        approximateCost: 0,
        duration: "1-2 hours",
        bestTime: "Morning",
      },
      {
        name: "Dudhsagar Falls",
        description: "One of India's tallest waterfalls (310m), cascading down the Western Ghats amid lush jungle",
        category: "Nature",
        approximateCost: 500,
        duration: "4-6 hours",
        bestTime: "November to February",
      },
      {
        name: "Fort Aguada",
        description: "17th-century Portuguese fort with sweeping views of the Arabian Sea and a historic lighthouse",
        category: "Heritage",
        approximateCost: 50,
        duration: "1-2 hours",
        bestTime: "Late afternoon for sunset",
      },
      {
        name: "Palolem Beach",
        description: "Crescent-shaped beach in South Goa known for calm waters, dolphin spotting, and silent discos",
        category: "Beach",
        approximateCost: 0,
        duration: "3-5 hours",
        bestTime: "Morning or sunset",
      },
    ],
    events: [
      {
        name: "Sunburn Festival",
        date: "2026-12-27 to 2026-12-30",
        description: "Asia's largest electronic dance music festival with top international and Indian DJs",
        venue: "Vagator, North Goa",
        category: "Music Festival",
      },
      {
        name: "Goa Carnival",
        date: "2027-02-13 to 2027-02-16",
        description: "A vibrant pre-Lenten festival with parades, floats, music, dance, and street performances",
        venue: "Panjim, Margao, Vasco",
        category: "Cultural Festival",
      },
      {
        name: "Feast of St. Francis Xavier",
        date: "2026-12-03",
        description: "Annual exposition of the saint's relics at Basilica of Bom Jesus, drawing pilgrims worldwide",
        venue: "Basilica of Bom Jesus, Old Goa",
        category: "Religious",
      },
    ],
    advisories: [],
    emergency: {
      police: "100",
      ambulance: "108",
      fire: "101",
      nearestHospital: "Goa Medical College, Bambolim — 0832-2458700",
      touristHelpline: "1800-111-363",
    },
    transport: [
      {
        mode: "Flight",
        from: "Major Indian cities",
        to: "Goa International Airport (GOI), Dabolim",
        cost: 3500,
        duration: "1-2.5 hours",
        details: "Direct flights from Delhi, Mumbai, Bangalore, Hyderabad. Airport to North Goa ~1 hr taxi",
      },
      {
        mode: "Train",
        from: "Mumbai, Delhi, Bangalore",
        to: "Madgaon or Thivim station",
        cost: 1500,
        duration: "8-14 hours",
        details: "Konkan Railway route is scenic. Sleeper class available. Book 2-3 months ahead in peak season",
      },
      {
        mode: "Taxi",
        from: "Within Goa",
        to: "Anywhere in Goa",
        cost: 500,
        duration: "Varies",
        details: "Prepaid taxi counters at airport and railway stations. ~₹15-20/km. Book online for better rates",
      },
      {
        mode: "Scooter Rental",
        from: "Local rental shops",
        to: "Self-drive across Goa",
        cost: 400,
        duration: "Per day",
        details: "Most popular way to explore Goa. Requires valid license. ~₹300-500/day. Fuel extra",
      },
    ],
    budgetInsights: [
      { category: "Accommodation", estimatedCost: 2000, notes: "Mid-range hotel or hostel per night" },
      { category: "Food", estimatedCost: 1200, notes: "3 meals + snacks at local/mid-range places" },
      { category: "Transport", estimatedCost: 500, notes: "Scooter rental + fuel split per person" },
      { category: "Activities", estimatedCost: 800, notes: "Water sports, entry fees, guided tours" },
      { category: "Miscellaneous", estimatedCost: 500, notes: "Shopping, tips, random expenses" },
    ],
    aiSuggestions: [
      {
        type: "weather",
        tip: "Thunderstorms expected on July 17. Swap Baga Beach with indoor options like the Goa State Museum or a cooking class.",
        priority: "high",
      },
      {
        type: "budget",
        tip: "Your group's ₹5,000/person budget fits North Goa better than South Goa. North Goa has cheaper stays and more budget eateries.",
        priority: "high",
      },
      {
        type: "transport",
        tip: "Renting 2 scooters for the group (₹400/day each) works out cheaper than taxis for 4 days of exploring.",
        priority: "medium",
      },
      {
        type: "food",
        tip: "Baga Beach shacks serve fresh catch at 30% less than Calangute. Try Souza Lobo for authentic Goan prawn curry.",
        priority: "medium",
      },
      {
        type: "general",
        tip: "Your Manali squad prefers adventure activities. Check out Scuba diving at Grande Island — it's ₹1,500/person and beginner-friendly.",
        priority: "low",
      },
    ],
  },
  manali: {
    overview: {
      description:
        "Nestled in the Kullu Valley of Himachal Pradesh, Manali is a breathtaking Himalayan getaway known for pine forests, snow-capped peaks, apple orchards, and adrenaline-pumping adventure sports.",
      bestTimeToVisit: "March to June (summer), December to February (snow)",
      language: "Hindi, English, Kulluvi",
      currency: "INR (₹)",
      timeZone: "IST (UTC+5:30)",
      quickFacts: [
        { label: "Elevation", value: "2,050 m" },
        { label: "Region", value: "Kullu Valley" },
        { label: "Known for", value: "Snow, treks, adventure sports" },
        { label: "Nearest Airport", value: "Bhuntar (50 km)" },
      ],
    },
    weather: {
      current: {
        temp: 18,
        condition: "Partly Cloudy",
        icon: "cloud-sun",
        humidity: 55,
        windSpeed: 8,
      },
      forecast: [
        { date: "2026-07-15", tempHigh: 22, tempLow: 12, condition: "Sunny" },
        { date: "2026-07-16", tempHigh: 20, tempLow: 11, condition: "Partly Cloudy" },
        { date: "2026-07-17", tempHigh: 18, tempLow: 10, condition: "Light Rain" },
        { date: "2026-07-18", tempHigh: 21, tempLow: 13, condition: "Sunny" },
        { date: "2026-07-19", tempHigh: 19, tempLow: 11, condition: "Cloudy" },
      ],
    },
    food: [
      {
        name: "Siddu",
        description: "Steamed wheat flour dumplings stuffed with poppy seeds, served with ghee and chutney",
        category: "Local Snack",
        priceRange: "₹50 - ₹100",
        tags: ["vegetarian", "local", "snack"],
      },
      {
        name: "Trout Fish",
        description: "Fresh Himalayan trout from the Beas River, pan-fried with local herbs and spices",
        category: "Main Course",
        priceRange: "₹350 - ₹600",
        restaurant: "The Johnsons Cafe, Old Manali",
        tags: ["seafood", "must-try", "dinner"],
      },
      {
        name: "Thukpa",
        description: "Tibetan noodle soup with vegetables or chicken, perfect for cold mountain evenings",
        category: "Soup",
        priceRange: "₹150 - ₹250",
        tags: ["tibetan", "warm", "dinner"],
      },
      {
        name: "Apple Crumble",
        description: "Manali is famous for its apples, and this warm crumble with fresh local apples is a must",
        category: "Dessert",
        priceRange: "₹200 - ₹350",
        restaurant: "Cafe 1947, Old Manali",
        tags: ["dessert", "local", "must-try"],
      },
      {
        name: "Dham",
        description: "Traditional Himachali thali with rice, dal, curd, and sweet pulao served on a leaf plate",
        category: "Thali",
        priceRange: "₹300 - ₹500",
        tags: ["traditional", "vegetarian", "lunch"],
      },
    ],
    attractions: [
      {
        name: "Solang Valley",
        description: "Adventure hub offering paragliding, zorbing, snow sports, and a scenic ropeway",
        category: "Adventure",
        approximateCost: 1500,
        duration: "4-6 hours",
        bestTime: "December to February for snow, May-June for paragliding",
      },
      {
        name: "Rohtang Pass",
        description: "High-altitude mountain pass (3,978m) with stunning glaciers, snow, and panoramic Himalayan views",
        category: "Nature",
        approximateCost: 500,
        duration: "Full day",
        bestTime: "May to October (closed in winter)",
      },
      {
        name: "Hadimba Temple",
        description: "Ancient cave temple dedicated to Hidimba Devi, set amidst a serene cedar forest",
        category: "Heritage",
        approximateCost: 30,
        duration: "30 min - 1 hour",
        bestTime: "Morning",
      },
      {
        name: "Old Manali",
        description: "Charming village with cobblestone lanes, riverside cafes, and a laid-back hippie vibe",
        category: "Cultural",
        approximateCost: 0,
        duration: "2-4 hours",
        bestTime: "Late afternoon to evening",
      },
      {
        name: "Jogini Falls",
        description: "A beautiful waterfall reachable via a short trek through apple orchards and pine forests",
        category: "Nature",
        approximateCost: 0,
        duration: "2-3 hours",
        bestTime: "Morning",
      },
    ],
    events: [
      {
        name: "Manali Winter Carnival",
        date: "2027-01-02 to 2027-01-06",
        description: "Annual winter festival with snow sports, local handicraft exhibitions, folk music, and dance",
        venue: "Manali Town",
        category: "Cultural Festival",
      },
      {
        name: "White Water Festival",
        date: "2026-10-15 to 2026-10-18",
        description: "River rafting competition and adventure sports festival on the Beas River",
        venue: "Beas River, Manali",
        category: "Adventure Sports",
      },
    ],
    advisories: [
      {
        severity: "low",
        title: "Rohtang Pass Permits",
        description: "Private vehicles require a permit to enter Rohtang Pass. Limited to 1,200 vehicles/day. Book online in advance.",
        source: "Himachal Tourism",
        date: "2026-07-01",
      },
    ],
    emergency: {
      police: "100",
      ambulance: "108",
      fire: "101",
      nearestHospital: "Kullu District Hospital — 01902-222106",
      touristHelpline: "1800-180-8077",
    },
    transport: [
      {
        mode: "Bus",
        from: "Delhi ISBT",
        to: "Manali Bus Stand",
        cost: 1200,
        duration: "12-14 hours",
        details: "Volvo AC buses by HRTC and private operators. Overnight buses depart around 6-7 PM. Book via RedBus",
      },
      {
        mode: "Flight + Taxi",
        from: "Delhi, Mumbai, Bangalore",
        to: "Kullu-Bhuntar Airport → Manali",
        cost: 6000,
        duration: "1.5 hr flight + 2 hr taxi",
        details: "Fly to Bhuntar (KUU) then take a prepaid taxi to Manali (~₹1,500-2,000)",
      },
      {
        mode: "Taxi",
        from: "Within Manali",
        to: "Local sightseeing",
        cost: 2000,
        duration: "Full day",
        details: "Full day taxi for local sightseeing ~₹1,500-2,500. Negotiate for Rohtang trips separately",
      },
      {
        mode: "Scooter Rental",
        from: "Manali rental shops",
        to: "Self-drive to nearby spots",
        cost: 500,
        duration: "Per day",
        details: "Scooters available at Old Manali. ₹400-600/day. Not recommended for Rohtang Pass — take a 4x4",
      },
    ],
    budgetInsights: [
      { category: "Accommodation", estimatedCost: 1500, notes: "Budget guesthouses or hostels per night. Old Manali is cheaper" },
      { category: "Food", estimatedCost: 1000, notes: "3 meals at cafes and dhabas. Old Manali cafes are very affordable" },
      { category: "Transport", estimatedCost: 1000, notes: "Shared taxi or bus for sightseeing, split among the group" },
      { category: "Activities", estimatedCost: 2000, notes: "Paragliding, rafting, or skiing depending on season" },
      { category: "Permits & Entry", estimatedCost: 300, notes: "Rohtang permit, temple entry fees" },
    ],
    aiSuggestions: [
      {
        type: "weather",
        tip: "Light rain expected July 17. Keep Jogini Falls trek for July 18 (sunny). Swap that day for Cafe 1947 and Old Manali exploring.",
        priority: "high",
      },
      {
        type: "budget",
        tip: "Your group's ₹8,000/person budget is comfortable for Manali. Book guesthouses in Old Manali (₹1,000-1,500/night) to save for paragliding at Solang.",
        priority: "high",
      },
      {
        type: "transport",
        tip: "Skip renting a scooter for Rohtang Pass — permits are limited and the road requires a 4x4. Book a shared taxi instead.",
        priority: "medium",
      },
      {
        type: "food",
        tip: "Try trout at The Johnsons Cafe — they catch it fresh from the Beas River. Best paired with a side of local apple cider.",
        priority: "medium",
      },
      {
        type: "general",
        tip: "Your squad's trip coincides with White Water Festival in October. Consider extending a day for the river rafting competition.",
        priority: "low",
      },
    ],
  },
};

export function getDestinationData(name: string): DestinationData | null {
  const key = name?.toLowerCase().trim();
  return destinationData[key] ?? null;
}
